
server:
 servlet:
    context-path: /cliente-pet/api
spring:
 data:
  mongodb:
    authentication-database: admin
    uri: ${MONGO_DB_URI:mongodb+srv://produdoroDevUser:123@cluster0.44owwzg.mongodb.net/?retryWrites=true&w=majority}
    auto-index-creation: true